[package]
name = "muehle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0"
rand = "0.8.5"
regex = "1.10.4"

[[bin]]
name = "agent"
path = "src/agent/main.rs"

[[bin]]
name = "game"
path = "src/game/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = "full"
